In [13]:
import pandas as pd
import numpy as np


1.Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de dado do array.

In [16]:
arr = np.random.randint(0, 100, size=10)

print(arr)
print(arr.dtype)

[52 48 48 47 31 48  3 44 87 25]
int32


2. Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.

In [17]:
import numpy as np

mat = np.random.rand(5, 5)

print(f"Valor mínimo: {np.min(mat)}")
print(f"Valor máximo: {np.max(mat)}")
print(f"Média: {np.average(mat)}")

Valor mínimo: 0.02200277313970289
Valor máximo: 0.9773038123835797
Média: 0.4932233750873919



3. Crie um array com 10 elementos aleatórios no intervalo [0, 1]. Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.

In [18]:
import numpy as np

arr = np.random.rand(10)

arr_int = (arr * 10).astype(int)

print(arr)
print(arr_int)

[0.18193024 0.96184428 0.93553625 0.68937106 0.97882442 0.64780672
 0.34185668 0.09620264 0.31717586 0.16752801]
[1 9 9 6 9 6 3 0 3 1]


4. Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]. Substitua todos os elementos da segunda linha por -1.

In [19]:
import numpy as np

mat = np.random.randint(0, 10, (3, 3))

mat[1, :] = -1

print(mat)

[[ 3  7  0]
 [-1 -1 -1]
 [ 1  5  9]]


5. Crie um DataFrame com as seguintes informações:
 - Coluna "fruta": "Banana", "Maça", "Pera"
 - Coluna "preco": 7.90, 10.20, 11.80
 - Coluna "quantidade": 12, 3, 4

In [20]:
data = {"fruta": ["Banana", "Maça", "Pera"],
        "preco": [7.90, 10.20, 11.80],
        "quantidade": [12, 3, 4]}

df = pd.DataFrame([["Banana", 7.90, 12],
                   ["Maça", 10.20, 3],
                   ["Pera", 11.80, 4]],
                   columns = ['fruta','preco','quantidade'])
df

fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4